### ISSUE TITLE
S-101 Issue with Surrounding Depth

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#10]
We need an attribute similar to surrounding depth which stores the shallowest underlying DRVAL1. Optionally,  an attribute which stores the shallowest DRVAL1 where DRVAL1 >= 0 could be provided to implement S-52 UDWHAZ05 continuation A as written.

ISSUE
In reviewing the S-101 portrayal catalog alert generation we discovered that when processing Obstruction and Wreck features with curve or area geometry more information is needed than is currently provided in surrounding depth.

Surrounding depth encodes the deepest DRVAL1 of underlying group 1 objects and is used in implementing CSP UDWHAZ05. In order to properly implement DEPVAL02/OBSTRN07/UDWHAZ05 Continuation A we require the shallowest DRVAL1. In the case of UDWHAZ05 Continuation A, the shallowest DRVAL1 which is >=0 is specified, but if you don’t mind isolated dangers showing up in these areas when SHOW_ISOLATED_DANGER_IN_SHALLOW_WATERS is on then we can just use the shallowest even when less than 0.

Note: This issue only affects Wreck and Obstruction features which have:
         Unknown depth (no valueOfSounding/defaultClearanceDepth)
         Multiple underlying DEPARE/DRGARE

**RELEVANT EXCERPTS:
DCEG:**
![DCEG1](https://user-images.githubusercontent.com/70211773/167567943-0fc44f9c-5712-4540-bec2-10012593bc41.png)

**S-52 DEPVAL02**
![image002](https://user-images.githubusercontent.com/70211773/167568207-5c7eb5bc-3a67-415a-bdff-aaaaa22b0b1c.png)

**S-52 UDWHAZ05**
![image003](https://user-images.githubusercontent.com/70211773/167568288-354b4584-3488-4824-826b-5c661f193195.png)

**S-52 UDWHAZ05 continuation A**
![image004](https://user-images.githubusercontent.com/70211773/167568430-d3f02170-c317-4b87-981e-a2c116ce678f.png)

**Comment by TDYCARHugh** [comment]
I think we are fine with only one surrounding depth value, the value of the deepest min depth (DRVAL1) of the surrounding water.
The main UDWHAZ05  conditional procedure does not call continuation A unless the surrounding depth is not deeper than the safety contour.  Therefore the loop in continuation A of surrounding water to see it if is in water shoaler than the safety contour is not necessary since continuation A is only called when the surrounding depth is not deeper than the SC.

**Comment by DavidGrant-NIWC** [comment]
> The main UDWHAZ05 conditional procedure does not call continuation A unless the surrounding depth is not deeper than the safety contour. Therefore the loop in continuation A of surrounding water to see it if is in water shoaler than the safety contour is not necessary since continuation A is only called when the surrounding depth is not deeper than the SC.

True, but earlier in UDWHAZ05 it checks "if DEPTH_VALUE <= SafetyContour". If that check fails then an alert will not be added, and the check you mention will never be evaluated.

In certain cases DEPTH_VALUE is assigned from the LEAST_DEPTH as returned by DEPVAL02. This LEAST_DEPTH should be the shoalest surrounding depth, but is currently the deepest surrounding depth. In order to fix this issue DEPVAL02 needs to be updated so that it matches the S-52 CSP, which requires that the shoalest of the surrounding depth range minimum values is used.

![image](https://user-images.githubusercontent.com/62906211/183446372-8cf5aeec-5e14-448d-8633-1262d9cd6710.png)

> The main UDWHAZ05 conditional procedure does not call continuation A unless the surrounding depth is not deeper than the safety contour. Therefore the loop in continuation A of surrounding water to see it if is in water shoaler than the safety contour is not necessary since continuation A is only called when the surrounding depth is not deeper than the SC.

**Comment by TDYCARHugh** [comment]
The CSP is trying to determine if the object is a hazard to navigation (depth of object< safety contour) and if it is in navigable water (deepest min surrounding depth). 
The depth of the object is ideally provided by valueOfSounding.  However, there are cases where an agency might not know the actual depth but they do know that there is at least X amount of water above the object and they should set defaultClearanceDepth.  We should not have to check for min surrounding depth in the portrayal because either the ValueOfSounding or the defaultClearanceDepth must be populated.  If these are not populated then I would expect it defaults to be considered dangerous.

The old S-52 CSP logic for when VALSOU is not given and assuming the object is as deep as the min surrounding depth -66 is replaced by the defaultClearanceDepth.

**Comment by DavidGrant-NIWC** [comment]
It's implemented as you describe, but I don't know that one of _valueOfSounding_ or _defaultClearanceDepth_ must be present. A lower multiplicity of "1" or greater doesn't prevent the attribute from being encoded as unknown. Is it guaranteed that the production systems will populate _defaultClearanceDepth_?

Here's the current implementation - I suppose we could remove the call to DEPVAL02 and keep the checks for _categoryOfWreck_ and _waterLevelEffect_? Is the rest of the group ok with that change? It would mean that some point features or linear/area features which only overlap a single depth area will also get flagged as hazards if they don't have one of the two attributes encoded.

![image](https://user-images.githubusercontent.com/62906211/183488496-731a5d98-08f6-4305-a811-22c6ece78540.png)

**Comment by TDYCARHugh** [comment]
The intention of defaultClearanceDepth was that it would simplify the CSP.  
How it gets populated is another discussion.  I have always wondered about how aware the producers are regarding the logic used in S-52 to determine the depth when VALSOU was not populated. ie logic based on WATLEV, EXPSOU and minimum surrounding depth and doing things like subtracting 66 from the least surrounding depth.  

I can understand that producers do not want to set Value of sounding if they don't have an actual measurement but they normally know (at least in normal shipping areas) that it is safe enough for vessels of a certain draft.  I would have expected producers to want to set defaultClearanceDepth based on knowledge of the area such as swept depth etc to be able to set the value to something they know to be safe rather than having a automated calculation based on assumptions.

**Comment by DavidGrant-NIWC** [comment]
To implement in the PC we need a decision - either:
* [ ] a) Require that one of _valueOfSounding_ or _defaultClearanceDepth_ must be encoded (can't both be unknown)
* [ ] b) Remove DEPVAL02 and let unknown depths get handled by _categoryOfWreck_ / _waterLevelEffect_ checks
    * May end up with more hazards then would otherwise be the case.
    * Can encode _defaultClearanceDepth_ to address this issue.
* [ ] c) Change multiplicity of _surroundingDepth_.
    * Despite the multiplicity changing, in the great majority of cases only a single value would actually be encoded.

**Comment by JeffWootton** [comment]
Based on the above discussion, have applied changes throughout the DCEG based on option (a) above.  Note that, as the value of defaultClearanceFDepth is based on the value of surroundingDepth, I have also included surroundingDepth in the changes (i.e. mandating if valueOfSounding = empty (null)).

To be discussed at the next DCEG Sub-Group meeting.

**Comment by alvarosanuy** [comment]
Agree in principle with option (a) but, are we happy on how **surroundingDepth** is calculated when a Surface/Curve feature (i.e. Wrecks) expands over multiple depth or dredged areas?? I believe we should go for the shoalest DRVAL1 and not the deepest one. It can be risky to assume that the section of the fetaure that sits on the 'deeper' area does not contain depths that may belong to the 'sholaer' side. The ENC producer, with their encoding, is telling us that the know anything about the feature (lets say Wreck for argumenta sake). Probably this type of encoding is very unlikely but technically possible. If an scenario like this exists, I would prefer to flag the Wreck as dangerous based on the worst possible scenario (populate **surroundingDepth** with the shoalest DRVAL1 value possible).

**Comment by JeffWootton** [comment]
Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Paper S-101PT11-06.1 and related decisions. Changes applied for S-101 Edition 1.2.0.

Close Issue.
