### ISSUE TITLE
Iso8211 Encoding : DDR field definitions : use of {} vs ()

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Documentation-and-FC#106]
For the generation of S-164 Test-DataSets, we have a doubt about Iso8211 definition of some fields in the DDR of these datasets. 

The fields concerned are in which we have concatenated+repeated elements.

Example from S-100_5.1.0_Final_Clean the definition CI3L field :

![C3il](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/24851994/a1a8d1c7-66fe-4100-8ca4-c14fd25d04a0)

**We need confirmation of the use of  {..} at the place (..)  .**

See The complete discussion in : https://github.com/iho-ohi/S-101-Test-Datasets/issues/78

**Comment by kusala9** [comment]
this is from 8211 (1994). the contents between the {..} specify the fields which are repeated. So, C3IL is composed of a single VCID followed by any number of {3 x b24} repesenting the coordinates. 

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/3368156/4a954295-defc-4782-bb1f-21eb0f8eeb85)

**Comment by himikof** [comment]
@kusala9 Thanks for sharing the relevant 8211 standard text! I'm afraid I do not see how you are able to come to the conclusion that `{}` are used to mark indefinite repetition from that.

Let me expand on the reasoning I briefly explained in iho-ohi/S-101-Test-Datasets#78:
1. The penultimate paragraph is the one that authoritatively defines the indefinite format repetition behavior:
  >If the data field is not exhausted, the format shall repeat from the left-hand parenthesis corresponding to the next to the last right-hand parenthesis not including those parentheses used to delimit field width and using the associated repetition factor if any. If there is no such right-hand parenthesis, format control shall revert to the first left parenthesis of the format specification.
  
Note that it is explicitly says "parenthesis"/"parentheses", which commonly mean round brackets `()`, not other types. It also refers to the "parentheses used to delimit subfield width", which are unambiguously defined only as `(*), (n)` above. Also note that there is no need/capability to explicitly mark any group as indefinitely-repeating, as the last two paragraphs quoted define an exact rule to determine which group (if any) is repeated indefinitely in any given format controls string.

2. The informal expression `({Y|mY|k(mY,...),...},...)` defining the format controls grammar is unfortunately not written in a well-defined language (like BNF, or PEG). It does not make an explicit difference between meta-language describing the structure and composition of the grammar, and literal symbols from the language of this grammar. Obviously, `|` is an example of the meta-language symbol (meaning "alternative choice"), and `A` is a literal terminal.
I am sure that the set of meta-language tokens used is `|`, `{`, `}`, `...`. You can see that all those are described in a common way, using wording "implies ...". I can guess that `{}` was chosen for the meta-language rule grouping (instead of the usual `()`) to disambiguate it from the literal `(`, `)` used in the grammar instead of a formal way to mark the literals.
Also note that there is no mention at all of "braces" or "curly brackets" in the 6.4.3.3 text (while parentheses are mentioned multiple times), thus reinforcing the interpretation of them only as a part of the grammar meta-language specific to this expression.

3. There is a bit weird/exceptional rule about a restriction on repetition of a format of (explicit) fixed-length bit strings, described partially in the last quoted paragraph. For example, `(B(40))` is described as non-repeating by it. But note that it says that to explicitly opt-in to repetition in this case, it needs to be "enclosed in an additional pair of parentheses" (and "two consecutive opening parentheses" later). So it can only mean `((B(40))`, not `({B(40)})`.

4. As an additional non-normative consideration, I've examined the source code of several ISO 8211 implementations, including [GDAL/OGR](https://github.com/OSGeo/gdal/blob/d398f64ec1965f70f8bb642f6027dfa438651a8a/frmts/iso8211/ddffielddefn.cpp#L585C22-L585C22), [py-iso8211](https://py-iso8211.sourceforge.net/tibbs/iso8211.html) from Tony J Ibbs (one of the authors of the ISO/IEC 8211:1994), and two separate relatively complete closed-source implementations. None of them support anything other than using `()` for grouping/repetition in the format control strings. In fact, every one of them will report an occurrence of `{` in this context as a format error.

Personally, when reading the S-100 text I previously assumed that `{}` notation was an inspired and, unfortunately, not explicitly documented way to mark the repeating part for the readers/implementers not intimately familiar with ISO/IEC 8211. But now I see the potential for confusion if taken literally, and I think it should either be explicitly documented the same way `□▲▼` are, or `{}` should just be replaced by `()` if this is not intended/wanted.

**Comment by DavidGrant-NIWC** [comment]
### Recommendations
1. Mark this issue `invalid` and close. The issues raised are inherited from S-100 and can't be addressed by modifying S-101.
1. This issue should be addressed by submission of a change proposal or paper to an upcoming S-100 Test Strategy Meeting or S-100 Working Group meeting. See https://iho.int/en/s-100wg
    1. Changes to S-100 are unlikely prior to publication of S-100 edition 6.

### Issue summary
There are multiple issues raised.
  1. Does ISO-8211 permit braces in the format control (I don't think it does)?
  1. Does ISO-8211 require parentheses in the format control when encoding tables (I don't think it does)?
  1. Additional related issues:
      1. there are inconsistencies in the use of repetition in the format controls (braces are not always used), for instance:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/f665833c-1330-41dd-9093-594a6bd60237)
      1. there are some other typos, for instance: 
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/99c5f8b1-47ca-48bf-ad68-e0d111ec2b91)

### Issue 1  - Braces
S-100 clearly shows the use of braces in lieu of parenthesis. Although this (in my opinion) extends ISO-8211, it doesn't really matter since there is currently no other data published in ISO-8211 format that I'm aware of (excluding S-57 ENC). There is nothing else to maintain compatibility with.
  * Changing S-100 is hard.
      * Changes may necessitate changes to production software.
  * Implementing support for braces in a S-101 parser is trivial.
    * I expect GDAL/OGR will be updated at some point to support whatever is in S-100.

### Issue 2 - Use of parentheses in the format control
* Each column of an ISO-8211 table shares a common data type, (in my opinion) it isn't necessary to explicitly indicate the data type of each data field.
  * See C.2.1: ![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/75c2ba4a-70eb-4815-9bdb-da3731e1abdf)
  * The following representations are all functionally equivalent:
    *  `▲YCOO!XCOO!DRVO!\\*YDRV!XDRV▲(2b24,b11,b24,b24)▼`
    *  `▲YCOO!XCOO!DRVO!\\*YDRV!XDRV▲(2b24,b11,2b24)▼`
    * `▲YCOO!XCOO!DRVO!\\*YDRV!XDRV▲(2b24,b11,(b24,b24))▼`
    * `▲YCOO!XCOO!DRVO!\\*YDRV!XDRV▲(2b24,b11,(2b24))▼`
    * `▲YCOO!XCOO!DRVO!\\*YDRV!XDRV▲(2b24,b11,(b24))▼`
  * It is trivial for a S-101 parser to support any of the above forms.

### Issue 3.i - Consistency in representation of repeated format controls in data descriptive fields
* If S-100 is updated then all the DDF's should be reviewed to ensure resolution of issue 2 is applied consistently throughout.

### Issue 3.ii - Typos
* If S-100 is updated then typos should be corrected as part of the DDF review.

**Comment by himikof** [comment]
Regarding Issue 2, I do not think that it is true from the 8211 point of view. Note that the quoted part (C.2.1) explicitly separates DR field description in 2 layers: data field as a (flat, varying-size) sequence of subfield values (with data type/extent assigned, but not necessarily labeled), and the inner field structure which arranges the subfield values into a (sequence of) vector/table/tensor, mostly according to the vector labels given in the DDR. Nowhere does the 8211 standard directly assign a meaning to "column type": data types are handled on the subfield value level (mostly with format controls), and all labels themselves are fully optional in many cases.
The highlighted part talks about a field with homogeneous types, even allowing the format controls to be fully omitted in some cases: for example, `2000;&%/G▲*A!B!C▼`, `2000;&%/G▲*A!B!C▲(A)▼` and `2000;&%/G▲*A!B!C▲(3A)▼` are completely equivalent. Or even `2400;&   ▼` is possible, describing a real-valued tensor with fully-dynamic unlabeled dimensions. I do not see how it is related to mixed-datatype fields.

The 8211 standard defines a strict way to get a sequence of datatypes when reading an instance of a data field with varying subfield values count by repeating a part of the format controls, without any reference to possible labels. For example, a generic reader implementation can efficiently parse any given data field instance into a flat JSON/CBOR list given only the field and format controls, deferring the structure/dimensions/labels interpretation for later. While I agree that `(2b24,b11,(b24,b24))`, `(2b24,b11,(2b24))`, `(2b24,b11,2(b24))` and `(2b24,b11,(b24))` are completely equivalent (according to the format controls semantics in 8211), saying that they are equivalent to `(2b24,b11,b24,b24)` or `(2b24,b11,2b24)` cannot even be an extension of 8211, because it changes the semantics of a previously-valid construct in an incompatible way.

So, as I see it, grouping is indeed required for tables in fields with non-homogeneous types in 8211.

Fortunately, I do not think that is an issue for S-101 as it stands, because all fields in use there already have their table repetitions marked in the format controls in S-100 spec. While I think that requiring all implementations to support an undocumented `{}` extension to ISO 8211 as unfortunate, I agree that it is trivial to support by interpreting them exactly as `()` which any implementation must have already supported and practical concerns of the difficulty of changing S-100 may outweigh that. But if at any future point existing inconsistencies in other S-100 field definitions would be corrected by a change to S-100, I think that simply replacing `{}` with `()` is likely be a backwards-compatible change. Or at the very least this could be explicitly documented in S-100 as an extension.

**Comment by DavidGrant-NIWC** [comment]
My point regarding Issue 2 is that it is possible to parse the data in the subject cases regardless of what ISO-8211 requires because the data fields within each column of a table are homogeneous. Describing the data type of each subfield (or if you prefer, the first data field of each column) is sufficient since it applies to all the entries in that column.

In any case, as you note it doesn't matter because this issue only affects encodings containing `DRVF` and/or `DRVI`.

**Comment by kusala9** [comment]
I think braces are allowed in 8211. They represent the grouping of an entity. 

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/3368156/44d76026-8e9e-4875-b165-8609fb166df3)

I would tend to agree with DAve, if the 8211 descriptions need clarification then it needs to be done at the S-100 level, not S-101. A paper to TSM would help explain if there are issues. @HolgerBolthein may be able to comment more as he was involved in the drafting of Part 10a closer. The DDRs are hardwired into Part 10a so it would need a correction to S-100 if there is a problem with it.

**Comment by HolgerBothien** [comment]
Hello,
very interesting discussion. Here comes my interpretation.
I agree with those that mentioned that curly braces {} are not allowed in format controls. @kusala9 : the text you have cited is the description of the expression language that is used to describe the content not the content itself. I know ISO8211 is hard to read and even harder to understand. The standard is not widely used at all and will not be maintained by the ISO anymore. Maybe time to think for an alternative format (GeoJson?).

But back to the {}. Unfortunately a change in S-100 introduces them in some places, they weren't there from the beginning. When this had happened I did not read the standard document carefully enough. So, we have errors in S-100, how we will deal with them is a different topic.

In general I interpret the ISO8211 so that the actual order of sub-fields is not described by the **_format control_** at all. The **_format control_** only specify the format of the sub-fields that are desribed in the **_array descriptor_**. ISO8211 6.4.3.2 gives the details.
I will it summarize here:
We can have:
**Subfield labels**
If the field consists of only one sub-field an optional textlabel can be stored. in this case there will be exactly one format control. An example is the 0000 field in S-57 : `0500;&□□□▲▲(b12)▼`

**Vector label**
Here we have an ordered list of sub-fields, the sub-field labels are separated by the '!' delimiter. 
An example is the CSID field in S-100:
`1100;&□□□Coordinate□Reference□System□Record□Identifier▲RCNM!RCID!NCRC▲(b11,b14,b11)▼`
Here we have three sub-fields, no repetition and exactly three format descriptions in the format control.
So far very easy, isn't it.

**Cartesian label**
Now it becomes a little more challenging.
Cartesian labels are supposed to be used when the field should contain data from a table. Though the concept is not limited to two dimensional tables we will only consider the two dimensional case. We can do that without loss of generality.
The description is that we have a vector of labels that describes the row of the table and a vector of labels that describes the columns both vectors are separated with the delimiter '*'. Technically this can be seen as a vector of vectors, the format controls are only defining the types of the innermost vector (The one most right in the array descriptor)
An example is the 'Arc coordinate filed in S-57.
`2600;&□□□Arc□coordinate□field▲STPT!CTPT!ENPT*YCOO!XCOO▲(2b24)▼`
Note, that the number of format controls correspond to the number of sub-fields right from the '*' delimiter (2).
The actual field will contain 3 * 2 entries, thus it has a fixed length.
A special case of the cartesian label is the one where the first vector labels are ommited (called the null vector label).
In this case the field contains a repetition of vectors. the number of repetitions is unlimited and may be 0.
Many examples can be found in S-57 and in S-100. Here I show the 2-D Integer Coordinate List field.
`2100;&□□□2-D□Integer□Coordinate□List▲*YCOO!XCOO▲(2b24)▼`
To follow ISO8211 literally, there should be a '!' left of the '*'. This is not used from day one in S-57, so the IHO interpretation of 
ISO8211 differs slightly from the standard but in a consistent way.
Wasn't to hard, or?

**Concatenated structures**
The last challenge. 
Concatenated structures can be used to combine the labels as described above in one field. Especially the combination of vector labels and Cartesian labels needs this type of definition. 
The array descriptor has the form : array_descriptor_1\\array_descriptor_2\\...\\array_descriptor_n
It is important to note that only the last array_descriptor in that list may have a null vector label. With other words all other array descriptors need to have a fixed length. The format control will contain the number of elements that is equal to the sum of the format descriptors for the single array descriptors. Grouping of format descriptors may indicate which controls belonging to which part. But this is not really necessary since an unambiguous assignment from each sub-field label to a format control is possible without this.
As an example we use the Information association field from S-100:
`3600;&%/GInformation□Association▲RRNM!RRID!NIAC!NARC!IUIN\\*NATC!ATIX!PAIX!ATIN!ATVL▲(b11,b14,2b12,b11,{3b12,b11,A})▼`
It is a concatenation of a vector label and a 2D Cartesian label with a null vector label. We have five sub-fields in the vector label part and another five sub-fields in the Cartesian label part. This correspond to the ten format descriptions in the format control. Any grouping to indicate the repetition of the last five sub-fields is not necessary. the repetition is already described by the Cartesian label in the array descriptor. Note that the {} in the example are not conforming to ISO8211. A correct version would be:
`3600;&%/GInformation□Association▲RRNM!RRID!NIAC!NARC!IUIN\\*NATC!ATIX!PAIX!ATIN!ATVL▲(b11,b14,2b12,b11,3b12,b11,A)▼` or
`3600;&%/GInformation□Association▲RRNM!RRID!NIAC!NARC!IUIN\\*NATC!ATIX!PAIX!ATIN!ATVL▲((b11,b14,2b12,b11),(3b12,b11,A))▼`
Again, the grouping is in my opinion not required but both variants are correct. Software should be robust enough to handle both cases.

**Conclusion**

- There is no need to introduce grouping format controls in the S-100
- Where grouping is already used it should be removed or at least corrected (to remove the illegal {} and use ())
- The summary I gave here could be part of the ISO8211 summary I have created for edition5.1. I volunteer to do the edit but would kindly ask for a review.
- Clarifications should be made in S-100 to encourage OEMs to do a robust implementation regarding the syntax of the **_format controls_** and determine the structure only from the **_array descriptor_**

If we not changing S-100 now it might be to late. We are still in the testing phase of the standard. Minor changes should not be a problem.
Any toughts?

**Comment by himikof** [comment]
> In general I interpret the ISO8211 so that the actual order of sub-fields is not described by the format control at all. The format control only specify the format of the sub-fields that are described in the array descriptor. 

Interestingly, this is the opposite of how I've interpreted subfield semantics in ISO 8211. I think that the format controls specify how to parse a field data area into a flat sequence of typed subfield values (with varying length per field instance). The 6.4.3.3 a) specifies the exact rules. And the array descriptor then specifies how to arrange those subfield values into a data structure of a few different kinds, often with some labels.

See the following example which is handled naturally by this approach, but is hard to interpret otherwise:
DDR: `2600;&□□□Dynamic□array□example▲▲(A(:),A(2),I)▼` [^1]
First DR contents: `2▲1▲3▲TEST:AA1▼`
This is a two-dimensional 1x3 array `[["TEST", "AA", 1]]`.
Second DR contents: `3▲1▲2▲3▲TEST:AA1▼FOO:BB2▼`
Now this is a three-dimensional 1x2x3 array `[[["TEST", "AA", 1], ["FOO", "BB", 2]]]`.

A even more complex example would be `2600;&□□□Dynamic□array□example□2▲▲(A(:),A(2),I,I)▼` where the field data could sometimes have 2x2 tail dimensions. The format controls could be arbitrarily complex too, with repetitions and nesting.

Of course, both interpretations are exactly equivalent if the number of subfields is constant and can be determined from the DDR, or even if the field is a singular table without concatenation (due to format controls auto-repeating as a whole by default per 6.4.3.3 a) ). Any implementation can still map formats/types to the labels/structure before reading the data as an efficiency optimization, but I do not think that 8211 allows to always demand it by omitting the grouping of the repeated format controls. 

Allowing such omission creates a dialect of ISO 8211 with slightly changed/incompatible semantics in an obscure corner case: `3600;&□□□▲A\\*B▲(I,A)▼` with data `1▲2▲3▲4▼` would be typed/parsed differently by those interpretations[^2], while `3600;&□□□▲A\\*B▲(I,(A))` is completely unambiguous. 
I would suggest that ISO 8211 is already complex and obscure enough as it is, and avoiding any possible ambiguity/implementer confusion by simply consistently using the grouping parentheses in the standard would be better.

[^1]: Empty array descriptor for 2xxx means a dynamically-shaped array, encoded as `n_dims▲dim_1▲...dim_n▲array_data`.
[^2]: Either as `{"A": 1, "B": ["2", "3", "4"]}` or `{"A": 1, "B": ["2", 3, "4"]}`

**Comment by DavidGrant-NIWC** [comment]
> * The summary I gave here could be part of the ISO8211 summary I have created for edition5.1. I volunteer to do the edit but would kindly ask for a review.

Recommend that you post it here.

**Comment by JeffWootton** [comment]
Close issue pending discussion at S-100WG level.
