### ISSUE TITLE
Encoding of speed limits

### ISSUE THREAD

**Issue by KlasOstergren-SMA** [iho-ohi/S-101-Documentation-and-FC#108]
There are inconsistencies in the DCEG and the data model regarding the encoding of speed limits.

17.4 Speed limits states:
> Speed is often limited inside harbours in order to prevent wakes. If it is required to encode this restriction, it must be done using a Restricted Area feature (see clause 17.8), with the attribute category of restricted area = 24 (no wake area) or restriction = 13 (no wake). If it is required to encode cases where the speed limit is known in general or for a certain class(es) of vessel, it must be done using restriction = 27 (speed restricted), with the speed limit, speed units and, if appropriate, the class of vessel, encoded using an instance of the complex attribute vessel speed limit, sub-attributes speed limit, speed units and vessel class.

At the same time, it is possible to encode restriction=27 (speed restricted) for several other features where the complex attribute vessel speed limit doesn't exist. 

I see three options:
1. Remove restriction value 27 (speed restricted) as an allowable value for all features other than Restricted Area
2. Add the complex attribute vessel speed limit to all features where restriction value 27 (speed restricted) is allowed
3. Amend the guidance in 17.4 to reflect the current situation
4. Leave as is

Any thoughts?

**Comment by alvarosanuy** [comment]
Agree with @Christian-Shom - **Option 2** is preferred. A validation check as proposed would provide 'logical consistency' and is also supported.
DCEG guidance could be modified as follows (**restriction** is the only mandatory attribute):

_Speed is often limited inside harbours in order to prevent wakes. If it is required to encode this restriction, it must be done using a Restricted Area feature (see clause 17.8), with the attribute restriction = 13 (no wake). The attribute category of restricted area should be also encoded using the value 24 (no wake area)._

**Comment by JeffWootton** [comment]
Based on the options proposed by Klas, I think there are really only 2 options:
- Option 2 as put forward by Klas;
- A combination of options 1, 3 and 4 (resulting in the requirement to encode RestrictedArea in all cases in order to encode a speed restriction).

I have no strong personal opinion on this. I will include this in the DCEG report to S-101PT12 for possible resolution. If this cannot be resolved there, I will be convening a DCEG Sub-Group meeting during April and it will hopefully be resolved there.

**Comment by KlasOstergren-SMA** [comment]
I have no strong opinions either and I'm fine with option 2. 
Regarding the wording in the DCEG, the simplest solutions is maybe to just clarify that the encoding of a known speed limit can be done by using any feature where restriction=27 is an allowed value.

**Comment by Richard-Fowle** [comment]
DK would support option 2

**Comment by JeffWootton** [comment]
S-101PT12 Decision: Apply changes as recommended in paper S-101PT12-05.1.1 (for S-101 Edition 1.3.0 draft). At this time no review of the logic for inclusion of speed restriction information on some S-101 features required.

Changes applied 08 march 2024. Close issue.
