### ISSUE TITLE
New allowable formats for S-101 Support Files?

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#113]
It has been suggested that additional file formats should be considered for S-101 support picture files (currently only .TIF). Please refer to email correspondence with Christina Ulrich (SevenCs):

[Support_File_Format_Correspondence.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/14206735/Support_File_Format_Correspondence.docx)

Noting previous discussions within IHO Technical Working Groups on this topic related to data security issues and the requirement to define a universally agreed format for the version of a file format, any opinions on this topic would be appreciated.

**Comment by kusala9** [comment]
there's an open issue on the topic in S-164 with a list of all the currently accepted formats. Currently it's 

* Text (UTF-8)
* TIF 6.0
* JPG2000

PDF is not supported, partly because of the difficulty in specifying the exact format, and partly because of the issues in supporting multiple palettes (day, night, dusk). 

There's still a question over supporting HTML which needs to be resolved but the above list is what's in the new draft of S-98 Annex C. HTML is in, for now, but only subject to having a more definite specification of what is available. There is an "other" category but that won't be able to be used for support files.

**Comment by DavidGrant-NIWC** [comment]
JP notes the formats allowed by S-100 & S-98, but JW is asking about the restriction in S-101:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/1e344025-f099-42af-9a03-2022feb5d300)

I don't think data security is a consideration since the files within an exchange set are exchanged in a secure manner. I also don't think TIFF has any particular advantage in terms of palette support.

Who would benefit from allowing additional formats, and would HO's actually utilize those new formats?

**Comment by TomRichardson6** [comment]
Propose retain as is, this has been discussed previously unless a clear use case exists propose close the issue.

**Comment by JeffWootton** [comment]
Rejected at S-101Pt12 for Edition 2.0.0. Principle reason is backward compatibility with S-57 for the dual-fuel period. Possibly discuss further after S-57 has been "sunset". Close Issue.
