### ISSUE TITLE
S-101PT12-06.19 Day of week

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-101-Documentation-and-FC#132]
Starting this issue to discuss the definitions for listed values representing days of the week.
Suggested "neutral" defintions:

- Sunday: The day of the week preceding Monday and following Saturday.
- (and so on for Monday, Tuesday etc.)

As discussed at S-101PT12, the numeric codes will not change.

This revision of definitions needs to be approved by other working groups with stakes in this attribute, especially NIPWG.

**Comment by TomRichardson6** [comment]
Support this proposal which avoids referencing any specific first day of the week. But we may wish to consider using the phraseology of in between rather than preceding and following, open to other comments here especially from those where English is not the first language. 

the [day](https://en.wikipedia.org/wiki/Day) of the [week](https://en.wikipedia.org/wiki/Week) between [Saturday](https://en.wikipedia.org/wiki/Saturday) and [Monday](https://en.wikipedia.org/wiki/Monday)

**Comment by JeffWootton** [comment]
I would personally prefer the definitions as suggested by Raphael rather than "in between" as it is not specific (for example, Monday is also "between" Sunday and Wednesday). However I would reverse the order so as to follow the natural progression: Monday -> Tuesday -> Wednesday ...

Therefore suggest: Sunday: The day of the week following Saturday and preceding Monday.

**Comment by JeffWootton** [comment]
No comments on changes applied for draft Edition 1.3.0.

Close Issue.
