### ISSUE TITLE
Remove value 6 (pontoon bridge) for category of opening bridge?

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#138]
S-101 data model for **Bridge** feature has been reviewed based on paper https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT10/S-101PT10_2023_07.6_EN_New_Data_Model_for_Bridges_V1.pdf and discussion at PT10.
In 1.2.0, **pontoon bridge** is an allowable attribute value 3 for **bridge construction** and value 6 for **category of opening construction.**
Classifying a pontoon bridge as opening does not describe the way the bridge opens: it may be a swing, bascule or draw bridge. 
In addition, it is "strange" to find one single concept in two different attributes.

**I suggest removing value 6 (pontoon bridge) as an allowable value for category of opening bridge.**

**Comment by TomRichardson6** [comment]
I understand that there are pontoon bridges which have opening components and one example is the Hood Canal Bridge in Washington State, USA. This is a Pontoon bridge where a drawbridge retracts so that vessels may pass through part of the bridge. 

Another example would be the pontoon bridges in the Suez canal one example is the Ahmed Omar Shabrawy pontoon bridge;

https://www.google.com/maps/place/30%C2%B002'43.1%22N+32%C2%B034'27.8%22E/@30.0450788,32.5744729,768m/data=!3m1!1e3!4m4!3m3!8m2!3d30.0453!4d32.5744?hl=en&entry=ttu

Another is the Ahmed el-Mansy pontoon bridge in both cases the entire pontoon rotates by 90 degrees so that vessels can pass.

https://www.google.com/maps/place/30%C2%B036'19.4%22N+32%C2%B019'31.4%22E/@30.6043779,32.3253992,1870m/data=!3m1!1e3!4m4!3m3!8m2!3d30.6054!4d32.3254?hl=en&entry=ttu

In order to remove the value as proposed it must be clear in the guidance that swing bridge should be used in such instances, to many I imagine a swing bridge is usually thought of as a fixed structure but the definition is broad enough to cater for a pontoon bridge as per the examples above. I'd welcome further views on this point. 

Going back to the Suez examples the El Ferdan railway bridge is a swing bridge but is very different from the pontoon bridges detailed above. 

https://www.google.com/maps/place/30%C2%B039'25.2%22N+32%C2%B020'02.4%22E/@30.6523444,32.3260246,1869m/data=!3m1!1e3!4m4!3m3!8m2!3d30.657!4d32.334?hl=en&entry=ttu

**Comment by HermanSchouten** [comment]
Agree with your point of view Christian. Glad you opened this item. It was something I was considering to mention, but was a bit reluctant to stir up whole new discussions on this topic.

**Comment by JeffWootton** [comment]
The value _6_ for attribute `categoryOfOpeningBridge` has bee removed and the opening pontoon bridge example amended to have the opening section encoded with `categoryOfOpeningBridge` = _3_ (swing bridge).

**Question:** Should the value for `categoryOfOpeningBridge` = _7_ (drawbridge) be amended to the now vacant value _6_?

**Comment by JeffWootton** [comment]
S-101PT13: Recommendations as included in Paper S-101PT13-06.1 and draft DCEG Edition 1.4.0 approved.

Close Issue.
