### ISSUE TITLE
S-101 Scale guidance

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#14]
To serve as a base for discussion in view of adding guidance in the PS, please find a table showing how Max. and Min. Display Scales could be set for S-101 datasets. I have voluntary created two options, one based on "traditional" S-57 CSCL, and another one with 3 scales ranges consistent with the specific usage metadata attribute that is used for cataloging.
**Please comment on this or provide other examples your organization may already have.**
The idea is to:
- determine basic rules to be followed (and "mistakes" to avoid, and
- provide various examples of what can be done.
[S-101_Scales_proposal.xlsx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/8927567/S-101_Scales_proposal.xlsx)

**Comment by forodd** [comment]
Thanks Christian for adding this base for discussion. We have not studied this in detail yet, just noticed that our current use of CSCL across usage bands is a bit different from the starting point in your overview.
Adding a list of NO CSCL usage for comparison, not claiming this is any better, just stating the fact that it is different from the examples in your table, and it will be a significant task to eventually rescheme it. 
[Norway_current_S57_CSCL_in_use.xlsx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/8966809/Norway_current_S57_CSCL_in_use.xlsx)

Assumuing other producers will also have their own distribution of CSCL since this has not been harmonized earlier.

Will this be targeted for post dual fuel or supposed to be ready by start of  S-101 provision? It seems hard to achieve anything less than a 1:1 conversion S-57 <-> S-101 during dual fuel?

**Comment by alvarosanuy** [comment]
Hi all,
We haven't looked at this thoroughly but our current preliminary approach indicates we will combine (in one HPD layer) S-57 NP 1 & 2 and call it OVERVIEW, continue managing NP 3 &4 in one HPD layer and call it TRANSIT and keep NP 5 & 6 as different HPD layers but publish both of them as PORT ENTRY. Note that NP6 is currently use for HDbENC only and our plan is to discontinue them (in favor of S-102) after the end of the DF period ......

I tried to identify the current S-57 and future S-101 cut off scales the best I could (_please read inline comment in cell A26_).
[Australia_current_S57_CSCL_in_use.xlsx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/9036143/Australia_current_S57_CSCL_in_use.xlsx)

**Questions @Christian-Shom**

1. Is the expectation that ECDIS will only transition/load a smaller scale S-101 dataset when the MSVS is =< MaxDS of an overlapping dataset (even when MSVS becomes smaller than MinDS)? If there's a gap between MinDS and MaxDS the preference would be for the larger scale dataset to continue being displayed 'under scaled' (SCAMIN should declutter content as required).
2. When zooming in, would ECDIS load a larger scale dataset when MSVS > MaxDS, irrespective of the MinDS of the larger scale dataset?? Consistent with approach in 1 above (larger scale dataset is loaded and displayed 'under scaled').
3. If there's no larger scale dataset to load, the existing one would be over scaled and should trigger an Indication when MSVS=> 2 X MaxDS

**Comment by JeffWootton** [comment]
Indications from the limited feedback received is that it will be very difficult to reach consensus on this Issue.

No comment since July 2022. Close Issue pending further discussion.
