### ISSUE TITLE
Encoding of bridge parts over land

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#146]
It is unclear to me on how should we encode parts of a bridge that are situated on land (when the part over navigable water is encoded with a Span (Fixed or Opening).
For more details, please refer to paper from Friedhelm in https://github.com/iho-ohi/S-57-to-S-101-conversion-sub-WG/issues/6.
As DCEG 6.7.1 and 6.8.1 states: "_**Span Fixed features should only be encoded if the span is entirely or partly over navigable water at the optimum display scale for the ENC data.**_"
which feature should we encode on the areas in blue in this figure?
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/71139640/cad5ce75-7dc3-47e8-8924-018ac8d8b3ec)
If in S-57 ENC, the real world object is encoded with 3 separate BRIDGE features, I guess they will be converted into 3 Spans, which contradicts the wording in the DCEG.

**Comment by HermanSchouten** [comment]
We also encountered this. We are currently changing all bridges in our S-57 Database, and are clipping the BRIDGE features so that they don't overlap LNDARE anymore.  
The areas marked in blue will be a ROADWY, so not representing reality. We have had some discussions on this.

**Comment by Richard-Fowle** [comment]
If areas in blue are still part of the Bridge then I think they should should be encoded as Bridge features. 
My thinking in this case is that the two Pylon features and one Span Fixed feature together with the two Bridge features would then all be associated using the Bridge Aggregation. Although if that is the case then perhaps Figure 6.2 should be extended to cover the parts of the bridge that are not over navigable water

**Comment by JeffWootton** [comment]
There should only be one bridge feature in the above example, covering the entire extent of the bridge. The two blue highlighted sections do not have to be encoded as individual spans if the data producer does not wish to do so due to the statement "Span Fixed features should only be encoded if the span is entirely or partly over navigable water at the optimum display scale for the ENC data." - this is relevant to the spans only and not the bridge itself. However, because this is a "should" and not a "must" the producer may wish to encode the spans that are entirely over land for completeness.

The span information is the information relevant to the Mariner for navigation (clearances etc) so the spans are only required to be encoded where part of the span is over navigable water at the scale of the ENC.

The issue of how these bridges are converted from S-57 is problematic. Because of the extensive remodelling from S-57 to S-101 there is no "easy" way to convert. I do not consider that issues with data conversion should be considered when looking at how bridges are modelled in S-101.

**Comment by JeffWootton** [comment]
Discussed at S-101PT13. Current guidance considered to be sufficient. It is up to the Data producer to decide how to encode their `Bridge` features and their associated spans.

Close issue.
