### ISSUE TITLE
Reference to Compilation Scale

### ISSUE THREAD

**Issue by Christian-Shom** [iho-ohi/S-101-Documentation-and-FC#17]
There is only one reference to Compilation scale in the S-101 PS (§4.5.3 : "The maximum display scale is considered to be the equivalent of the compilation scale of the data.")
I am of the same opinion as Alvaro (post meeting November 2021) that this reference to Compilation Scale should be deleted from S-101 documentation for the benefit of scale range (and Max/Min Display Scales).
CSCL is used for S-57 ENCs; Max/Min DS will be used for S-101 ENCs (including the loading strategy) and quoting the Compilation scale in S-101 PS brings no useful information.
Moreover, the term "compilation scale" is misleading, as currently digital data is often compiled at a much larger scale than the one at which it is intended to be displayed.

**Comment by TomRichardson6** [comment]
Support the removal of this reference for improved clarity

**Comment by alvarosanuy** [comment]
I support the removal of this text.

**Comment by Christian-Shom** [comment]
Thanks Mikus for this interesting input.
My view is that with the end of Usage Bands and the introduction of Max and Min Display Scales, we are switching to a different model and that getting rid of compilation scale may be the best option.
As "Compilation Scale" only appears once in the current PS, I would suggest removing it for edition 1.1.0. 
If it is later felt that it needs to be reintroduced, further work would be needed to propose ad hoc wording.

**Comment by MikkoHovi-FI** [comment]
I think @MikusRL does have a point. 

All charts, even S-101, do have a scale (or scale range) they are compiled to. Otherwise things will get messy. This is regardless of how we call the scales in S-101. We should be careful not to go so far with avoiding certain terms, that the cartographers not already familiar with S-101 will have difficulties understanding what we are trying to say.

It is not necessary to use the specific term "compilation scale" towards the end user or even inside the product, but in the production process it still exists. Therefore, I think, it may still have its place in the PS when discussing the scales. 

That said, I am not sure if the current text in 4.5.3 is completely true. As @Christian-Shom said, with the Max and Min Display Scales, the compilation scale should basically and ideally be seen as scale range - from Max Display Scale to Min Display Scale. This scale range is the scale the chart would optimally be compiled to. However, I believe, that many HOs will still pick one single scale to which they compile their data - the compilation scale.

**Comment by RichardCoyles** [comment]
I feel the reference to Compilation Scale should remain in the PS because HO's will be concerned with attributing MaxDS & MinDS to the Display Scale Range (DSR) during conversion (S-57 to S-101). I would be difficult to assign the DSR without first understanding the optimum display scale, and its equivalent in S-57 (The Compilation Scale)
Also, because overscale is such an important function in ECDIS, it should indicated accurately, and therefor MaxDS should be the equivalent to the Compilation Scale in S-57.

**Comment by Christian-Shom** [comment]
Due to lack of consensus, the Sub-Group meeting 2022-10-19 agreed on keeping the wording as it is (retain reference to Compilation).

**Comment by JeffWootton** [comment]
After the editing session at S-101PT10 (November 2022) the single instance of the term "compilation scale" has been removed from Edition 1.1.0 of the S-101 Main document. There is only one instance of the term in S-100 (Part 16, clause 16-11.7). Further, the term "compilation scale" does not appear at all, nor is it defined, in S-4. The term does exist in the IHO Hydrographic Dictionary, however this is purely related to ECDIS and was formerly in S-32 Appendix 1 - Glossary of ECDIS Related Terms. Consideration may be given to retiring this term when S-57 is "sunsetted".

There are 5 instances of the term "compilation scale" in Edition 1.1.0 of the S-101 DCEG. For consistency, based on decisions at S-101PT10 and changes made in the Main document, these instances have been replaced with "maximum display scale of the data" for Edition 2.1.0. Close issue pending outcome of discussions at S-101PT11.
