### ISSUE TITLE
Foul Ground - Curve Primitive

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#29]
Refer to S-101 Portrayal issue #65: (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/65)

Outcome of Portrayal Sub-Group meeting July 2022:
5.  DCEG subWG to discuss the need (use case) for geometric primitive Curve for this feature type (currently not allowed in S-57).

Looking back on the development notes for the DCEG, I could not find any justification for the inclusion of the curve primitive as an allowable attribute for the S-101 feature FoulGround.  The FoulGround feature was originally adopted as a duplication of the Obstruction feature so as to separate foul ground (not dangerous to surface navigation) from obstructions (dangerous to surface navigation).

Discussion at the S-101 Portrayal Sub-Group meeting in July 2022 questioned the requirement for curve primitive as an allowable primitive for FoulGround.  No use case could be identified during this meeting and the action has been subsequently passed to the DCEG Sub-Group.

Unless a use case can be identified for the retention of curve as an allowable primitive for FoulGround, this will be removed as allowable encoding for S-101 Edition 1.1.0.

**Comment by Christian-Shom** [comment]
Not specialist in navigation use cases, but could not there be a need to encode linear Foul grounds (such as chains) on very large scale ENCs?
If not, OK for removing curve as an allowable primitive.

**Comment by alvarosanuy** [comment]
**I did a quick research and I found that:**

1. In S-57, OBSTRNs can be Point, Areas or Lines (I couldn't find anything that prohibits the use of Lines when CATOBS=7). This would make the statement from the quoted PsWG action, incorrect.
2. S-101 **FoulGround** feature also allows for P,L and S geometry types (same than S-57).
3. Point and Surfaces with CATOBS=7 (with or without VALSOU populated) are not run through the CSP. **For some reason, geometric primitive Line does go through the CSP (only CATOBS=8 9 10 and WATLEV=7 are excluded).** This means that the portrayal of Foul Ground lines may change and display the 'isolated danger symbol ' on the line when VALSOU is either not populated or shoaler than the SC. This does not happen to OBSTRN; CATOBS=7 Point or Surfaces (with or without VALSOU)  They have set symbology (see below).

Extract from S-52 LUT
![image](https://user-images.githubusercontent.com/70189016/194206602-dd4dc510-a41d-483e-acdb-4a0efc682948.png)

4. The PsWG has developed a unique portrayal for **FoulGround**  features of geometric primitive Line. NIWC to confirm they are run through CSP OBSTRN07 as per S-52 (to be confirmed in order to evaluate consistency against S-52).
5. We are happy to retain Line geometry for **FoulGround** but the new question for us is:

- [ ] Do we want run Foul Ground Line features through CSP but not P and S ??  Why??

**Comment by Christian-Shom** [comment]
- Whatever the final decision, all primitives must be treated equally.

- In addition to my comments and associated paper in https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/30:
If the S-101 Portrayal rules are identical to S-52, that means that CATOBS 8, 9 and 10 (and WATLEV 7) will not go through CSP OBSTRN07 and never trigger alarms. Consequently, such objects are never dangerous to surface navigation and should be Foul Ground (OK for ground tackles, not for booms that floats and my be quite "big".
Isn't there a need to review CATOBS allowable values and associated Portrayal?

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  2.2, 2.5.9, 13.7

Points to Note:
-  Proposal is to remove curve as an allowable geometry for the feature FoulGround.
-  Note that curve (line) is prohibited for foul ground in S-57 (UOC 6.2.2).
-  Are there any use cases for allowing curve?

Discussion/Decision:
-  No significant discussion on this issue.  On investigation, it was confirmed that the guidance in the S-57 UOC was that foul ground (OBSTRN, CATOBS = 7) should only be encoded as point or area, although as a “should” this is a strong recommendation but not mandatory.

**Action:**
**-  Remove curve as an allowable geometric primitive for the FoulGround feature for DCEG Edition 1.1.0.  [Complete]**
**-  Summarise discussion in the GitHub and close issue (IHO Sec).**
