### ISSUE TITLE
Sector Extension

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#5]
Actions S-101PT4-14 and S-101PT4-15 and Paper S-101PT4-5.5:  Sector Extension portrayal attribute.
Please see attached discussion thread (read from bottom up).  Besides improved guidance in the DCEG, suggestions for revised modelling include:
-  Renaming the feature to sectorArcExtension; and 
-  Amending to type Boolean so as to extend the arc by a default defined distance.

[Sector_Extension_Discussion.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/6608728/Sector_Extension_Discussion.docx)

**Comment by JeffWootton** [comment]
Here is the original S-101PT4 paper:

[S-101PT4_2019_05.05_EN_DCEG_Sector_Extension_Portrayal_Attribute_V1.pdf](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/6608751/S-101PT4_2019_05.05_EN_DCEG_Sector_Extension_Portrayal_Attribute_V1.pdf)

**Comment by DavidGrant-NIWC** [comment]
> I like Hugh's thinking regarding renaming the attribute and changing the type to Boolean, and would appreciate anyone else's thoughts on this.

Rename the attribute: 👍 
Change the type: 🤔 

Can there be more than two overlaps? If so, S-52 would overlap the extended arcs, whereas S-101 currently allows the producer to set the extensions to whatever they desire, including partial overlaps (S-101 extension resolution is 1mm as opposed to 5mm).

![image](https://user-images.githubusercontent.com/62906211/121081193-5c30c580-c7aa-11eb-955f-51ecf5d54c87.png)

**Comment by alvarosanuy** [comment]
Support the change of name.
In regards to amending the attribute to boolean, I think the key factor there is to agree on the default extension distance to use. In my opinion it should be linked to the 'sector light length' behavior which has now been discussed (https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/3) and approved in principle by the portrayal subWG and the S101PT Chair. Changes to the NIWCs PC to support further testing by Norway has been approved and findings/recommendations are expected to be presented at the next S101PT meeting in November 2021 (refer to S-101 actions PortSG-05 and 06).

**Comment by HannuPeiponen** [comment]
Hugh Astle wrote in an email (31st May 2021):
"I agree that it should not be up to the ECDIS to determine if the arc extends beyond the actual nominal range of the light. The producer could however consider the intended scale of the ENC and be careful not to extend the arc beyond the range of the light when displayed at compilation scale"

I share the view of Hugh, namely:
- ENC producer sets values of both "compilation scale" and "actual nominal range of light"
- If it is important that the sector light length does not extend over the actual limit on displayed chart then the producer can set appropriate "compilation scale" so that the sector light length does not extend over the actual limit

If the "compilation scale" method is not acceptable, then the group could consider to abandon the idea of extension of sector lights. If so then the sector lights drawn to show nominal range would always be displayed at nominal range exactly (this is how S-52 operates).

My final comment is that I do not know from where this issue originates. The S-52 had two user selectable style: a) fixed drawing of light sectors being 20 or 25mm on the display (easy to detect by user that the display style is not related to nominal distance); and b) drawing based on nominal distance without any extensions/exceptions (easy to detect that the display style is related to nominal distance). I have never heard any request to change this in S-52. Have we tried to be "too clever" for the portrayal of S-101?

**Comment by JeffWootton** [comment]
Taking into consideration that all discussion on the name of this attribute should be amended to Sector Arc Extension, without any objections to this change, the name has been amended.  Close Issue.
