### ISSUE TITLE
S-101 complex attributes, delete and PAIX shift

### ISSUE THREAD

**Issue by halset** [iho-ohi/S-101-Documentation-and-FC#56]
PAIX is defined in B5.1.14, B5.1.15, B5.1.32, B6.1.10, B6.1.11, B6.1.31 like the following:
> Index (position) of the parent complex attribute within this ATTR field (starting with 1). If the attribute has no parent (top level attribute) the value is 0

If an update data set file remove an attribute in a list that has a following complex attribute, the indexes are shifted, but the PAIX values are not. This result in an inconsistent complex attribute tree as the PAIX-values are now pointing to other attributes.

How should this be handled? By not allowing the deleting of an attribute when a complex attribute are after that attribute in the list? Or by deleting all attributes and re-add them with updated PAIX-values? Or by adding a unique node id to keep the tree consistent even when the indexes are shifted? 

We (ECC) have implemented a set of validation checks on the attributes to prevent data with inconsistent complex attribute trees from being imported.

**Comment by LeoKuzmin** [comment]
Hi,

It looks like ECC is treating PAIX erroneously.

According to S-100 Edition 4.0.0 document (10a-4.1.1) it must be treated as following:

_To specify the parent of the attribute an index is used. This index points to the nth tuple in the ATTR field starting with 1._
 
![image](https://user-images.githubusercontent.com/106175259/199033952-44fa92b8-3df8-4774-90e5-42c0e0e8c406.png)

I.e. **PAIX is an ordinal number, not an constant index of the attribute**
It is mandatory to modify all attribute parents prior to modifying the attribute itself:
![image](https://user-images.githubusercontent.com/106175259/199034103-5a4d56d5-737d-480f-9c5e-f9b110201730.png)

In this example if we remove attribute A3 deletion A4 PAIX will still be 0 and A8 PAIX would be 9.

If we had only two last modify instructions (marked with red), the table would look like this:
![image](https://user-images.githubusercontent.com/106175259/199034204-d9f4ab82-db6f-4053-8262-f0da7338af99.png)

Regards,
dKart team.

**Comment by halset** [comment]
Thank you for the examples, @LeoKuzmin.

> ![image](https://user-images.githubusercontent.com/445229/199051462-4548c6c3-fa50-4c13-833b-f75a5a0b2879.png)

With this as a basis, lets say an update is deleting A1 and nothing else. A5 still has PAIX=2. Earlier parent of A5 was A2, but now parent of A5 is A5 itself - and that is not legal. Will such an update modify PAIX of A5 to PAIX=1? And modify the other PAIX-values to fix the linking as well?

We have seen in some production tool from someone else that only the last attributes could be deleted. My assumtion was that this was done to prevent old PAIX-values to point to other attributes.

**Comment by LeoKuzmin** [comment]
Looks like we say about different things. The standard describes storing and transferring of data. As far as I understand, your questions refer to the applying of updates in a tool.
For your example, yes, an update will contain only one tuple of the ATTR field. In that case A5 will still has A2 as its parent.
PAIX and ATIX is not a members of attribute entry within attributes tree. It’s used only for store/restore tree structure from flat container (ISO-8211).
If you apply this update and store the dataset as Re-issue or New Edition, yes, PAIX sub-fields of rest attributes must be redefined in the ISO8211 structure.

**Comment by halset** [comment]
If an ER-file has a FRID with RUIN 3 (modify) and some ATTRs with ATIN 3 (modify), how are the attributes to match? So far, I have converted the NATC to ATCD using the table in the beginning and then looked for matching ATTR in the EN-file using the (converted) ATCD, the ATIX and the PAIX. Is that correct? Or are the ATIX/PAIX values for use internally in the ER-file only?

This has worked for ER-files from one vendor, but now I am looking at the ER-files from another vendor and there not all of the ATIX/PAIX of ATTRs with ATIN 3 in the ER match have corresponding ATIX/PAIX values of the same FRID in the EN-file.

**Comment by HolgerBothien** [comment]
Leo is absolutely right with its explanations.
The PAIX is only valid within one record and will not be preseved in the SENC structure.
The identification of an attribute works with the code (NATC) and the attribute index (ATIX). Those values must be preserved in the SENC. The ATIX values may change due to deletion and/or insertion of attributes with the same code. This is all mentioned in the S-100 Part 10a - 4.1 Attribute Field. 
Can you give an example where you are in doubt how to encode it.

**Comment by HolgerBothien** [comment]
I had a first look.
It seems that they want to delete the first _sectorCharacteristics_ attribute. (from 6 existing)
The method they used is:
_sectorCharacteristics_ [1] = _sectorCharacteristics_ [2]
_sectorCharacteristics_ [2] = _sectorCharacteristics_ [3]
_sectorCharacteristics_ [3] = _sectorCharacteristics_ [4]
_sectorCharacteristics_ [4] = _sectorCharacteristics_ [5]
_sectorCharacteristics_ [5] = _sectorCharacteristics_ [6]
and then delete _sectorCharacteristics_ [6]
This is possible the most complicated way of doing it. :-) 

The correct way should be:

| idx | ATCD | ATIX | PAIX | ATIN | ATVL |
| --- | ---- | ---- | ---- | ---- | ---- |
| 1 | sectorCharacteristics | 1 | 0 | 2 | |

A few observations:
1. why are there 6 _information_ attributes with no content in the ER file?
2. Though the method is nothing but efficient in the modifications are those that do even do not change anything because the new value is the same as the old value.

**Comment by halset** [comment]
> The correct way should be:
> 
> |idx|ATCD|ATIX|PAIX|ATIN|ATVL|
> |---|----|----|----|----|----|
> |1|sectorCharacteristics|1|0|2|

Applying this would then delete idx 1 from the EN-file as ATCD, ATIX and PAIX match. All of those with PAIX=1 will also be deleted and so on in a recursive tree. Is this correct?

What will then happen to the rest of the ATTRs that are left after that delete? Will the PAIX-values be shifted implicit to keep the consistency of the tree? Or will the tree now be inconsistent as the indexes has shifted?

**Comment by HolgerBothien** [comment]
Again, PAIX values are only local. When an attribute is deleted as in the example above the ATIX values of the remaining attributes with the same code and the same parent in the tree are shifted. i.e. was formerly was ATIX=2 will now be ATIX=1 etc.
This must be considered on subsequent changes to the attributes of the object. That is conceptional not different from updating coordinates or other ordered lists.
Production software should create the most efficient update and receiving software must be interpreting that correctly.

**Comment by halset** [comment]
Thank you. I now have a working implementation of this that works good with all of the examples in 10a-4.1.2 and the test data we have from multiple vendors.

Here are some feedback to https://iho.int/uploads/user/pubs/Drafts/S-100%20Ed%205.0.0_Final.pdf 10a-4.1.2 that can perhaps make this a bit less confusing for others.

* In the first table, it says that B3 is to change to 32, but in the table below it is changed to 22 instead. Should this be fixed?
* In the second table, index 4 it remarks "A10 - now with ATIX 2". Should this be changed to ATIX 3? Or when is "now" in this context?
* In an update file, PAIX is (as you have written) for defining the tree *inside* the file only and ATIX is for reference/ordering in the base/combined data structure. Can this distinction be expressed more clearly in the documentation?
* The example is very good, but a step by step explanation of how the insert/modify/delete of a set of complex attributes could be useful.

**Comment by HolgerBothien** [comment]
Thank you Tore,
The first to points should be corrected; the second has been detected by Svein and by myself already. I have a proposal for changes for the next S-100 WG meeting.
I agree that the documentation can be aproved but I would like to have some proposals how to do it.
It can be discusssed during the meeting next week.

**Comment by skjeves** [comment]
For information:
During S100WG7 in December 2022 it was accepted that we should propose our clarifications to the S100 Test Strategy Meeting in March 2023.

**Comment by skjeves** [comment]
@HolgerBothien @halset 
I am preparing for the TSM9 meeting in a couple of weeks, and think we should try to propose clarifications ref @halset bulletpoints above: 

- In an update file, PAIX is (as you have written) for defining the tree inside the file only and ATIX is for reference/ordering in the base/combined data structure. Can this distinction be expressed more clearly in the documentation?
_My proposal is to add the following text to S-100 10a-4.1.2 after 1st sentence:
"The Parent Index (PAIX) is solely used for defining the tree inside the file only, and is not preserved in an internal system (e.g. SENC) structure. The identifiaction of an attribute is defined by the Numeric Attribute Code (NATC) and the Attribute Index (ATIX). ATIX values may change due to deletion and/or insertion of attributes with the same code, and as such ATIX is to be used for reference/ordering in a base/combined data structure"._

- The example is very good, but a step by step explanation of how the insert/modify/delete of a set of complex attributes could be useful.
_Agree that an example could be valuable here, @HolgerBothien you may have an idea for an example? (you being the 8211 guru I suspect you have been involved also with the existing examples:) Perhaps an example added in addition to the existing one in 10a-4.1.2 could be feasible?_

Any input would be much appreciated.

**Comment by skjeves** [comment]
@HolgerBothien @halset would you be able to help with an example as suggested in previous post? Would also be good to get your feedback on the proposed added text (bullet 1 previous post).

**Comment by JeffWootton** [comment]
Changes applied to S-100 Part 10a in accordance with the above.  Close issue.
