### ISSUE TITLE
Consider modifying `NauticalInformation` so that `pictorialRepresentation` is part of `information`

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#69]
`NauticalInformation` is used to reference support files. `information` is a mandatory complex attribute (1:∞). `pictorialRepresentation` is optional, but must be used when referencing a support file containing a picture (which must be in TIF format).

Currently, to reference a support file, the encoder must create an empty `information` attribute (because it's mandatory) along with the `pictorialRepresentation` attribute.

Recommend either moving `pictorialRepresentation` into the `information` complex attribute, or make `information` optional (0:∞) and update DCEG 2.4.12.1 and 2.4.12.2 accordingly.

**Comment by JeffWootton** [comment]
I am not sure where this is coming from. The complex attribute **information** and the attribute **pictorial representation** for the **Nautical Information** information type are "conditionally mandatory", in that at least one of these must be populated for each instance of **Nautical Information**. This means that, if **pictorial representation** is populated with a picture file reference, then complex attribute **information** does not need to be populated, and vice-versa (see DCEG clause 24.4).

I have double-checked throughout the DCEG and have found no instance where it states that information is a mandatory (complex) attribute for **Nautical Information**.

Perhaps I am missing something here? Discuss in DCEG Sub-Group.

**Comment by TDYCARHugh** [comment]
@JeffWootton This appears to be another case of the DCEG and XML FC not matching.
In the DCEG the definition of Nautical Information has the binding as 0,* with the note about the mandatory conditionality as you say.   In the  XML Feature catalogue the binding to information from NauticalInformation is mandatory. With the lower bound set to 1.
			<S100FC:attributeBinding sequential="false">
				<S100FC:multiplicity>
					<S100Base:lower>1</S100Base:lower>
					<S100Base:upper xsi:nil="true" infinite="true" />
				</S100FC:multiplicity>
				<S100FC:attribute ref="information" />
			</S100FC:attributeBinding>

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  This appears to be an inconsistency issue between the DCEG and the Feature Catalogue. Investigations appear to indicate that the requirement as outlined in this Issue is covered by the DCEG but is incorrect in the Feature Catalogue.

**Discussion/Decision:**
-  The meeting agreed that there was no issue with the DCEG, however the Feature Catalogue needs to be corrected for the next version (Edition 1.2.0).

**Action:**
**-  Ensure that this inconsistency is addressed in the next (Edition 1.2.0) version of the Feature Catalogue (IHO Sec).**

Problem still exists in first draft of S-101 Edition 1.2.0 Feature Catalogue, however has been reported as a comment against Issue #98.

Close Issue.
