### ISSUE TITLE
S-101 Text Placement cartographic feature

### ISSUE THREAD

**Issue by JeffWootton** [iho-ohi/S-101-Documentation-and-FC#7]
Please refer to paper [S-101PT7-12](https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-101PT7/S-101PT7_2021_12_EN_CARIS%20proposal%20to%20amend%20S-101%20TextPlacement%20Attribution%20in%20S-101%20Ed%202_V%202.pdf) and discussions that have taken place within the ECDIS Portrayal Sub-Group ([#30](https://github.com/S-101-Portrayal-subWG/Working-Documents/issues/30)).

**Comment by JeffWootton** [comment]
Initial draft changes to the DCEG in regard to the modelling of the cartographic feature TextPlacement, and resultant changes intended for S-100 Edition 5.0.0, were included in DCEG Edition 1.0.2.  Further enhancement, in particular to the encoding guidance, is required for Edition 1.1.0.  The current draft for TextPlacement (clause 23.1) is attached.  The only change applied in this draft from Edition 1.0.2 is the removal of the textJustification attribute, which from intersessional discussions is not required in the revised modelling.

Any suggested amendments/enhancements will be greatly appreciated.

[DCEG Clause 23.1.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/9584349/DCEG.Clause.23.1.docx)

**Comment by TDYCARHugh** [comment]
The property 'orientation value' is ok but without reading the description it might be confused with how the text should be rotated. A name like 'bearing from feature' or 'offset direction' might be more intuitive.

It was at one point agreed that testJustification may not be needed for example to always refer to the centre of the text.  The normal justification values don't make sense when you consider the map might be rotated and text flipped so left becomes right and vice versa.  With further implementation testing there may be proposals such as to define that the placement is to the closest side of the text as opposed to the centre.  If you don't know the length of the string (such as if it is translated) then it might be difficult to define a centre based placement where the text does not land on the feature.

**Comment by alvarosanuy** [comment]
> The property 'orientation value' is ok but without reading the description it might be confused with how the text should be rotated. A name like 'bearing from feature' or 'offset direction' might be more intuitive

Agree that the attribute names should be changed. I propose replacing **textOffsetmm** & **orientationValue** with:
**textOffsetDistance** & **textOffsetBearing**.
The units of measurement, etc are detailed in the corresponding sections describing all feature attributes (27.170 & 27.134). They could be also be mentioned in the encoding guidance itself.

Also, the following topics are still open and need to be discussed and addressed:

- [ ] The need or benefit of having a new attribute to allow the rotation of text (some thought that was the purpose of the, now discontinued, **_flipBearing_** attribute). This would complement the text offset concept. See image below to better visualize the practical applicability of this concept.
![image](https://user-images.githubusercontent.com/70189016/191878143-027d8207-68d6-4e3c-89a8-0f3351fc9fa3.png)

- [ ] The need or benefit of expanding the allowable values for the attribute **textType**.

Some other questions:

- Will **textPlacement** have its dedicated Text Group layer? Should we clarify that, when **textPlacement** is encoded, ECDIS must not display the 'corresponding' text populated in the Geo feature itself (i.e Light Description String; TG=23 in S-52); even when the TG for **textPlacement** is switched off ? In short, ensure that **textPlacement** display setting always wins ?
- Should we clarify that **textPlacement** must not be encoded when **textType**=name and the Boolean attribute **displayName** (in the associated feature) is False? This could be controlled by a Validation check.

**Comment by Christian-Shom** [comment]
- In favour of studying an additional attribute that would allow the rotation of text.
- "_**Should we clarify that, when textPlacement is encoded, ECDIS must not display the 'corresponding' text populated in the Geo feature itself**_" : Yes, this is not clear when reading the current guidance in the DCEG.

**Comment by JeffWootton** [comment]
**Summary of discussions at DCEG Sub-Group Meeting 3 (05-06 October 2022):**

DCEG Clause:  23.1

Points to Note:
-  Stress that this feature is one of the most important features in terms of testing so as to get this right.
-  Only change since Edition 1.0.2 is the removal of the attribute textJustification.  Consider that this is sufficient for 1.1.0 for testing purposes.
-  Note suggestions from Hugh and Alvaro for name changes to attributes: textOffsetMm -> textOffsetDistance and orientationValue -> textOffsetBearing.
-  Regarding Alvaro last point:  Perhaps there is an argument here, given that TextPlacement is a discrete feature with allowable attribute scaleMinimum, to include guidance to the effect that TextPlacement may be encoded where it is considered that the name should be displayed at larger display scales.  Not sure however how this would work with the displayName attribute on the geo features – will need to be discussed and tested.

Discussion/Decision::
-  It was reported that the only change made to the TextPlacement cartographic feature from DCEG Edition 1.0.2 was the removal of the textJustification attribute. It was also reported that now that S-100 Edition 5.0.0 was on the verge of being approved for adoption by the MS, the implementation and testing of the remodelling of this feature could now commence in S-100 testbeds.  As a result of this testing it is expected that the encoding guidance, and possibly the modelling, may be refined for DCEG Edition 1.2.0.
-  The renaming of attributes from textOffsetMm -> textOffsetDistance and orientationValue -> textOffsetBearing was generally supported, however it was agreed that a full proposal (including revised definition(s)) was required and would be considered for Edition 1.2.0.
-  It was agreed that the guidance would be significantly enhanced by the inclusion of Figures providing examples of the application of TextPlacement (for Edition 1.2.0).

**Action:**
**-  Results of monitoring of the implementation of the revised modelling for TextPlacement to be reported in the GitHub Issue # 7 (All).  [Ongoing]**
**-  Full proposal to be developed to rename (and possibly re-define) attributes textOffsetMm -> textOffsetDistance and orientationValue -> textOffsetBearing (IHO Sec, AU, T-Caris).  [For Edition 1.2.0]**
**-  Figures demonstrating the implementation of TextPlacement to be provided for inclusion in the DCEG (All).  [For Edition 1.2.0]**

**Comment by MikusRL** [comment]
@JeffWootton Was there also a brief discussion or proposal during the meeting to use for the texts better "Angle" than "Bearing"? This was to easier distinguish between navigational Bearing values and Cartographic feature placement values. But I might remember this one in association with similar but not this discussion. Just ignore this one if this was not for this case.

**Comment by alvarosanuy** [comment]
I'm trying to put together some draft changes to the DCEG around this topic and I have some general questions/concerns around the feasibility of text placement implementation, particularly if 'Heads-Up' display mode is selected:

1. My assumption is that the offset vector would point to the bottom left corner of the text (when North is Up).
2. Not sure how ECDIS currently manages text readability in 'Heads Up' display option (at mariner's request). Is this an S-52/S-64 requirement that has now been migrated to S-98/S-164)? I believe we want to retain the relative position of the text from the associated feature (because we decided that position avoids the text clashing with surrounding features/text). Also, the expectation would be that, if the reading of the text, from the bottom of the ECDIS screen, becomes compromised (i.e. ship navigates 180 degrees True and mariner selects 'Heads Up' display), ECDIS should 'flip' the text accordingly to support its reading .... In this case, the bearing/distance vector would not point to the bottom left corner of the text anymore and it would probably point to the top right corner instead (??).
3. I like the possibility of including a new attribute called **textOrientation** (True Angle?) to manage the orientation of the text from the end of the offset vector defined by the bearing/distance values (refer to the image above). Having said this, it may all be too complicated to manage by ECDIS in Heads-Up mode though .....

I may be overthinking all this but your input to help me clear my mind and better understand requirements would be highly appreciated.

**Comment by rmalyankar** [comment]
S-98 Annex C says only that S-101 and other Product Specifications utilize _TextPlacement_ to optimise placement of labels and it can provide for placement of: text relative to a point, along a line, and relative to an area using a local coordinate reference system. As I recall it that was written when the old version of _TextPlacement_ was in use.

**Comment by DavidGrant-NIWC** [comment]
> 1. My assumption is that the offset vector would point to the bottom left corner of the text (when North is Up).

Generally it should point to the horizontal and vertical center of the text at all times. Here I've simulated associating a text placement feature containing text "North" located at a distance of 5mm and bearing of 0 degrees from all `Mooring/Warping Facilities`. Center/Center text alignment is to (try to) prevent the text from rendering on top of the symbol as the chart is rotated.
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/b2999310-3c34-40e3-a73b-6916473bd9df)

> 2. [How is the text oriented]

The text is always upright, and it's anchor position remains fixed as the chart rotates. 

|0|90
|:---:|:---:|
|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/b2999310-3c34-40e3-a73b-6916473bd9df)|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/dd897806-d619-481a-b94c-632fc17644ba)|
|180|270
|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/3140f762-f7ff-4b53-b2ff-d0c89f428bec)|![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/e0980fb8-edd6-4187-8334-555a37b01bbb)

Zooming will change the geographic position of the text anchor since the anchor point is a fixed distance in mm from the symbol. Here I've zoomed out one time (no rotation) and you can see the text moving into the unsafe water:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/d04f4899-b37e-4fde-9477-49d40810dc18)

> 3. I like the possibility of including a new attribute called textOrientation (True Angle?) to manage the orientation of the text from the end of the offset vector defined by the bearing/distance values (refer to the image above). Having said this, it may all be too complicated to manage by ECDIS in Heads-Up mode though .....

The ECDIS isn't doing anything other than drawing the drawing instructions output by the portrayal. The portrayal will examine the feature and output the appropriate drawing instructions to visualize the text as desired. If you want the text to rotate as it moves around the symbol, we can just set the rotation to GeographicCRS so the text orientation stays fixed relative to the orientation of the chart (like rotating a piece of paper with text on it) here at 180:

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/9f26ce54-0928-4f08-adb7-deb91aa7d7a3)

Looks odd though since the symbol doesn't rotate, and none of the other text on the chart rotates. It does do a better job of preventing the text from hitting the symbol when the rotation is 90 or 270:
![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/5e8f456c-3260-40f8-818c-03ea727f4395)

**Comment by alvarosanuy** [comment]
Thanks Dave. I have drafted a proposal for the new attributes (bearing & distance) that I will share with some of you for input before S101PT11 and I'm now of the opinion that **textOrientation** would only work as expected in North Up mode and could cause unwanted clutter and confuse readability when in Heads Up mode. Therefore I will not pursue this idea for now.

**Comment by alvarosanuy** [comment]
**For discussion**- Change proposal for **TextPlacement** and 'associated' key attributes (**textOffsetBearing** & **textOffsetDistance**).

[DCEG Text Placement_New Attributes definitions.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/12471620/DCEG.Text.Placement_New.Attributes.definitions.docx)
[DCEG Text placement_Feature definition_amended.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/12471621/DCEG.Text.placement_Feature.definition_amended.docx)

**Comment by KlasOstergren-SMA** [comment]
Spontaneously, I'm not in favour of the proposal to define the distance and bearing to the centroid of the text string, but I want to hear Hugh's view on this. 
My understanding of the idea behind Hugh's concept (the current data model) is that it will work independently of screen rotation by changing the reference point of the text string based on the screen rotation. This will prevent the text from clasching the point feature. CARIS have done a prototype implementation of this which we (SMA) have tested and it looks promising. We will be reviewing this together, hopefully next week when Hugh is back from leave.

I can agree that there are some cases where it might be relevant to associate a text placement feature with a curve or surface feature. The disadvantage of doing using this for curve and surface, compared to using the regular text label, is of course that the text might be placed off-screen and then not be visible to the user. 
If you want to place the text relative to the centre of the curve or surface, all you need to do is just to place the text placement point at that position and fill in the attributes.

**Comment by LARRIVEEJCANADA** [comment]
I am agree that we move on with the North up Display (majority of cases) cases and then work on the Head Up display.  We need to obtain a good solution for the majority of cases dans then work on the worst cases.  Just to know, can we consider auto-masking display into ECDIS or this is NOT an option into the ECDIS?

**Comment by alvarosanuy** [comment]
@JeffWootton **Note current DECEG statement in yellow below:**

<img width="337" alt="image" src="https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/70189016/be00c8d5-0983-4d68-85b9-0d457c5239b8">

Too ambitious and we know we do not have a solution for this yet. I think we can't '**ensure**' anything.
Maybe is a good idea to remove or rephrase this statement?

**Comment by JeffWootton** [comment]
Refer to Paper S-101PT11-06.1 and associated Action S-101PT11-12. The required changes and enhanced guidance has been included in S-101 Edition 1.2.0. As the modelling and implementation of TextPlacement requires further rigorous testing, this issue is to remain open.

One question regarding the attribute textType, which has multiplicity [0..1]: Could this be amended to [0..2] to allow for both the name and the light description to be placed?

**Comment by DavidGrant-NIWC** [comment]
> One question regarding the attribute textType, which has multiplicity [0..1]: Could this be amended to [0..2] to allow for both the name and the light description to be placed?

You wouldn't want both name and description to be placed at the same position.

**Comment by JeffWootton** [comment]
The `TextPlacement` cartographic feature data model and associated encoding guidance has been updated in accordance with the decisions taken at the S-101PT13 meeting, with further modifications made as a result of portrayal discussions and a further dedicated meeting to finalize the data model. The changes are summarized as:
- The attribute `text` has been removed as an allowable attribute (the text to be placed by `TextPlacement` can only be derived from the attribution of the target feature).
- Multiplicity of attribute `textType` has been amended from [0..1] to [1..2] to allow both the name and characteristics of the target feature to be placed using a single instance of `TextPlacement`.
- `textType` value 2 (light characteristics) has been amended to "feature characteristics" to facilitate placement of all characteristic related text.

Close issue. Further issues may be raised as a result of implementation and testing.
