### ISSUE TITLE
Adopting a single Vertical Datum for S-101 Datasets

### ISSUE THREAD

**Issue by TomRichardson6** [iho-ohi/S-101-Documentation-and-FC#72]
Proposal raised by SevenCs as part of wider discussions on vertical datums. 

Having said this, I want to go one step further. The reason is that we must see S-101 not longer as an isolated data product but in conjunction with other products especially S-102 and S-104.
One challenge (among many others) there is: Water level adjustment and depth value substitution only work if all the data are based on the same vertical datum.
Allowing multiple vertical datums will make it practically impossible to implement that features and present it in a transparent way to the end user. That should be the main goal, we shouldn’t forget this.
That’s why my final recommendation would be:

All depths and height information within one dataset must be based on the same vertical datum.

It had been possible to solve the problem for horizontal datums, why it should not be possible to solve it for the vertical case too.
It would even improve the usability of the dataset when they used as standalone data.
The problem that the end user cannot see directly which depth and height values are based on which datum already exists in S-57/S-52 from day one.

**Comment by KlasOstergren-SMA** [comment]
Even if I can see merits of the proposal of using only one vertical datum for all depth and heights in a dataset, I can also see some problems:
•	IHO resolution 3/1919 (as amended) states that heights should be referred to a highest water datum (eg. Highest Astronomical Tide) and that depth normally should be referred to LAT or equivalent in tidal areas. 
•	If the data producer use a datum for heights according to the resolution, how would the mariner know that? This is a safety question to have enough margin under bridges, pipes and cables.
•	When a tidal area, area with negligible tide or a non-tidal area meets within an ENC, the chart datum needs to be changed.  One way to solve this could be to split the ENC but that will cause trouble for data producers using a regular grid.

I don't see a need of referring single objects to a different datum but there is a need of using areas that refer to different datums.

**Comment by JeffWootton** [comment]
While I see some merit in discussing this in the S-101PT, this is ultimately an issue for the NCWG as the Working Group responsible for the maintenance of S-4. The relevant clauses are B-302, B-380.1, B-405 and B-413.

Having both a sounding (chart) datum and a height datum is essential in establishing the margin between the drying (chart datum) line and the coast (high water) line (the intertidal area) on charts where tide is appreciable. How is this going to be achieved if all depths and heights are related to a single datum?  How is the coastline and drying line going to be defined independently? How is an intertidal (drying) sounding going to be distinguished from an elevation?

In addition to Klas' comment (with which I agree):
- It is essential for safety reasons on charts that clearance heights are quoted against a high water datum.
- For many coastal States, charted low water lines and, also in many cases high water lines, are embedded in national legislation's.

I recall that, a few years ago, this issue was discussed within the NATO DGIWG in regard to "littoral" maps combining both topographic map and nautical chart information in a single product. There was no resolution for establishing a single datum for such a product reached at the time - mainly because of the comments that I have made above.

**Comment by MikkoHovi-FI** [comment]
To add to Jeff's comment above - even S-4 builds on IHO Res 3/1919 as amended on this topic.

**Comment by JeffWootton** [comment]
Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Papers S-101PT11-06.1 and S-101PT11-08.10, related decisions and Actions S-101PT11-40 to 42. Changes applied for S-101 Edition 1.2.0 at DCEG clauses 3, 3.3, 3.9 and 3.10.

Close Issue.
