### ISSUE TITLE
Recommend changing ValueType of `stationNumber` from integer to string.

### ISSUE THREAD

**Issue by DavidGrant-NIWC** [iho-ohi/S-101-Documentation-and-FC#86]
Creating a separate issue for this concern raised by @rmalyankar in https://github.com/iho-ohi/S-101-Documentation-and-FC/issues/85#issuecomment-1693771830

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/62906211/26cf0f36-dddb-46a3-be9e-fbd61c8ee7c3)

**Comment by SylviaSpohn-BSH** [comment]
We support the issue as we have in Germany gauge station numbers with letters. See our paper presented at the DCEG Subgroup Meeting 5./6.9.23.
[Paper for Consideration T_SPAD.docx](https://github.com/iho-ohi/S-101-Documentation-and-FC/files/12547091/Paper.for.Consideration.T_SPAD.docx)

**Comment by JeffWootton** [comment]
I would be interested in the background behind the "P" in the example included in the Paper from Germany.  If this is the identification letter intended to be included in the magenta diamond as it appears on teh paper chart, this should be populated in featureName (name) and not as part of teh station number.

**Comment by SylviaSpohn-BSH** [comment]
The letter „P“ is definitely part of the gauge number. The letter in the magenta diamont, that is used to link the object with a table in paperchart is used in an internal attribute, because it is used for paperchart, only. 
![grafik](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/72885087/7a429109-0e2e-4cfb-ba1f-e05dc177bf5f)

**Comment by JeffWootton** [comment]
**Discussion at S-101 DCEG Sub-Group 4 meeting:**

**Points to Note:**
-  See also draft paper submitted for S-101PT11 from Germany.

**Discussion/Decision:**
-  There was not a lot of discussion on the due to lack of time, however comments indicated approval of the proposal.
-  [After meeting note: Refer to Jeff Wootton (IHO Sec) comment 14/09/23 in the GitHub. Need to confirm that the “P” in the DE example is actually a part of the station number. If it is then should it be called “station number”?]

**Action:**
**-  Include draft amendments to the DCEG in line with the recommendations in the GitHub and draft Paper submitted by DE (IHO Sec). [Complete]**

Refer to discussions at DCEG Sub-Group 4 meeting (September 2023), Paper S-101PT11-06.1 and related decisions. Changes applied for S-101 Edition 1.2.0.

Close Issue.
