### ISSUE TITLE
Iso8211 Encoding : Update DataSet/Delete Feature

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Documentation-and-FC#95]
The S-101 product specification document , in the chapter "B-6 Update DataSet Structure" of a Feature Record , the field "FOID" is mandatory. see below

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/24851994/56ebd0d5-6282-43d4-880c-a90947439070)

When a feature is deleted (ruin = delete) in the FRID field , the field "FOID" is useless. 

I guess the fact to set field FOID mandatory in S-101 comes from the specification ENC/S-57 in which effectively the multiplicity was set to one. This lead to a situation when you want, in S57,  to delete a feature , you have to encode an empty value for FOID 

![image](https://github.com/iho-ohi/S-101-Documentation-and-FC/assets/24851994/efeef463-a160-4890-988b-9be66c06a5e8)
 
I think it is the occasion to simplify the situation in S-101 : I propose to set the multiplicity to 0, ..1 , in the B-6 Update DataSet Structure" => This will avoid to encode FOID field (empty or not) when a S101 feature is deleted.

**Comment by mikan66** [comment]
We operate in ISO8211 space for updating.  We currently "copy" all elements (FRID and FOID) of the feature update record if  RUIN = MODIFY.  This makes it required for our processing for MODIFY.  We do this because, from the specification it is not clear what the RUIN value implies for FOID field if RUIN = MODIFY.    What is being modified if RUIN = MODIFY in the Feature Type Record?  If you make this change, then more clarification is needed for "what do to" or "what can be modified" if RUIN = MODIFY at the Feature Type Record level.

**Comment by JeffWootton** [comment]
Is this a similar situation to Issue #90 ?

If the answer to the above is yes, then suggest applying a similar change by amending the multiplicity of FOID to `[0..*]` for the Update Dataset structure and developing a validation check to enforce conditional requirements.

Draft change made to B-6 pending discussion at the S-101PT13 meeting.

**Comment by plebihan29n** [comment]
Yes it looks like the issue #90, as they have the same conclusion : they require both a validation check to valid an update dataset exchange.
The difference is that change for this issue #95 concerns the field FOID for **update dataset** , as  the change #90 the change concerns the field CUCO for **base dataset** (for this last case, the validation check concerns the same field CUCO but in an update dataset structure).

**Comment by JeffWootton** [comment]
Change approved at S-101PT13. Close Issue.
