### ISSUE TITLE
QoBD features and Mandatory attributes

### ISSUE THREAD

**Issue by benhazelgrove** [iho-ohi/S-101-Documentation-and-FC#96]
**3.7 Quality of bathymetric data**

AHO are testing the ability to degrade an area due to **temporal variation**.

During our investigations we have found the following:

**QualityofBathymetricData** features have a Mandatory attribute **surveydaterange** date end. We don't see a use case for this attribute to be mandatory for areas that will never downgrade. We currently do not have attributes populated in our S-57 database for SUREND and SURSTA on our M_QUAL features. During conversion, following the current guidance, we will have a missing mandatory attribute for all our **QualityofBathymetricdata** areas.

A better use case for this would be as follows:

Where we identify an area that is likely to degrade, we would populate **categoryoftemporalvariation** with a value of 2 or 3 (most cases 3 - likely to change but significant shoaling not expected) and we would downgrade the **categoryofzoneofconfidenceindata** by 1 value (i.e. A2 to B). In this instance we would see a better use case to have **fixeddaterange**  **dateend** as a conditional mandatory attribute for the first value and **fixeddaterange** **datestart** for the new value of category of ZOC.

Due to the fact that an area could be made up of multiple surveys, the use of **fixeddaterange** as opposed to **surveydaterange**, would be a better use case. Therefore removing the need for **surveydaterange** **dateend** as a mandatory attribute at all.

At the moment there is some ambiguity in the DCEG. **3.7.1.1** **Temporal variation** describes using the survey date range fields when category of temporal variation is used, whereas Remarks bullet point 5, sub bullet point 2 of **3.7 Quality of bathymetric data** (DCEG 1.2.0) refers to the use of fixed date range when category of temporal variation is being used (the sub-complex attribute fixed date range is used to define the date range(s) where the quality is degraded over time).

We believe this can be clarified using the example we have provided.

**Comment by JeffWootton** [comment]
The population of the surveyDateRange (dateEnd) is intended to provide a frame of reference to the Mariner where the indication is provided that the bathymetry in the area is changeable through population of the categoryOfTemporalVariation attribute (as stated in DCEG clause 3.8.1.1). This was included at the insistence of the Data Quality Working Group (DQWG) as it was suggested that in many cases the Data Producer may not (or will not) be prepared to populate multiple instances of the zoneOfConfidence complex attribute to provide the visual representation in the ECDIS display of degrading quality over time. This is why the guidance in DCEG clause 3.8.1 5th Remarks bullet is not mandatory (should rather than must). In such cases the Mariner is provided with the capability to make a judgement as to the reliability of the bathymetry included in the dataset for the changeable area based on the date of the survey; without including this reference date from which the Mariner can make an assessment the identification of an area as changeable does not provide all the relevant information for such an assessment to be made. Even with multiple instances of zoneOfConfidence, the DQWG considered that surveyDateRange (dateEnd) would be useful in assisting the Mariner in making a more informed decision than relying only on the visual indication of the bathymetric data quality as encoded in zoneOfConfidence.

If the intention of AHO is to indicate degrading quality over time using multiple encoded instances of zoneOfConfidence and you consider that there is no requirement therefore to include a survey date, the option would be to encode datEnd for surveyDateRange as empty (null).

The complex attribute fixedDateRange cannot be used instead of surveyDateRange to provide this indication as fixedDateRange is used only to define the date range whereby an instance of QualityOfBathymetricData is displayed in the ECDIS.

**Comment by benhazelgrove** [comment]
AHO's intention is to do as follows:

Populate a QOBD area feature with its attribution as it stands on date of publication. i.e. Area is zone of confidence - A1; category of temporal variation 3 (likely to change) with fixed date range of 01/01/2024 (start) - 31/12/2024 (end). The area would then be changed to value 2 of zone of confidence - B; with fixed date range 01/01/25 (start) - (null) (end). This is based on determination of survey appraisal team that this area is no longer A1 after 12 months.

This would facilitate the change in the ECDIS display for the overarching area.

The point features within the area (soundings, rocks, wreck, obstructions) would be populated with the same line of thinking for Spatial Quality. They would have the values determined from their capture report encoded against Spatial Quality attributes and the same corresponding fixed date range as the area they sit within. A 2nd set of Spatial Quality attributes are also added that will downgrade those features to the corresponding values for the area as it has now changed. The fixed date ranges will match the QOBD area feature.

As we could be populating that area from more than one survey activity, the use of Survey date range doesn't make sense. AHO sees more use case for the downgrade of the QOBD area based on the date of publication. Therefore that area in its entirety would be changed via fixed date range.

**Comment by JeffWootton** [comment]
Refer to Paper S-101PT12-06..2 and outcome of discussions at S-101PT12.

If there is an issue with surveyDataRange being mandatory, then suggest that this could be "conditionally" mandatory based on a single instance of zoneOfConfidence only and categoryOfTemporalVariation = 1, 2 or 3.

**Comment by alvarosanuy** [comment]
> If there is an issue with surveyDataRange being mandatory, then suggest that this could be "conditionally" mandatory based on a single instance of zoneOfConfidence only and categoryOfTemporalVariation = 1, 2 or 3.

The AHO believes **surveyDateRange** should only be used in **SurveyQuality** features, not **QoBD**.
**QoBD** are areas containing bathymetric information sourced from multiple surveys. Any dates linked to this feature should be to manage the validity of the encoded ZOC accuracies. A **QoBD** may correlate to one survey data only but, we believe, those cases are exceptions not the rule.
In any case, information about surveys are to be encode in **SurveyQuality**. This feature can then be associated to a **QoBD** (if required/preferred).

**Comment by JeffWootton** [comment]
Refer to Decisions and Actions from S-101PT12. Draft changes applied to DCEG for Edition 2.0.0 in accordance with decisions from S-101PT12.

Close Issue.
