### ISSUE TITLE
S-164 : 3.1 ENC Display/Other/Mangrove

### ISSUE THREAD

**Issue by plebihan29n** [iho-ohi/S-101-Documentation-and-FC#99]
Just for advice and confirmation, look at the issue 64 from S-101-Test-Datasets
https://github.com/iho-ohi/S-101-Test-Datasets/issues/64

We have try to convert in S-101 the S-64 mangrove objects  in a way to be conform to the S-101 encoding guide.

Do you confirm the current encoding for area and line mangrove objects ? and if possible answer to the current questions :

1 : I find strange to not encode quality of measurement on the coastline even if the "mangrove area" is now in the display base display category (!= S-52). This quality information could be confirm that the coastline is not accurate.
2 : You write "I don't think default clearance depth should be populated (because the feature is not underwater):" : is it a rule from the DCEG ? . Perhaps could be useful to encode it for example ? if yes , I guess that the value is -5m as I have encode a height of 5m ?

Nb : For a next version, I wonder if "ENC Display/Other" is the good dataset to propose examples of accurate encoding. These "ENC display" Datasets are "roughly" datasets just to my understanding to check the setting of display categories. and in turn I guess that the good place for this kind of S-101 encoding examples have to be translated to "power up datasets" or somewhere else.

**Comment by JeffWootton** [comment]
Mangrove encoded as Obstruction can only be encoded as geometric primitive point or surface (see Issue #102).

Where encoded as Obstruction of type surface, the seaward edge of the mangrove should have attribute qualityOfHorizontalMeasurement = _4_ (approximate).

Obstruction has conditional mandatory attributes height or valueOfSounding dependent on whether the obstruction is always dry (in which case height is mandatory) or not (in which case valueOfSounding is mandatory). Because mangrove trees only exist in the intertidal area and portions of the tree are always dry, the guidance mandates the population of height for mangrove, in which case defaultClearanceDepth is irrelevant. Do you think this needs to be stated in the DCEG?

If mangrove is to be encoded as a line feature, it mut be encoded as a Coastline feature. The guidance in the DCEG in this case is as follows:

"If it is required to encode mangroves in the intertidal area, this should be done using an **Obstruction** feature (see clause 13.6). However, on smaller optimum display scale ENC datasets where the mangroves are required to be encoded to indicate the seaward edge of a mangrove area only as the “apparent” coastline, this must be done using **Coastline** with **category of coastline** = _7_ (mangrove). The coastline’s spatial type should have the attribute **quality of horizontal measurement** = _4_ (approximate)."

I think this covers your point 1 above, noting also that the same requirement exists for the seaward edge of the mangrove area when encoded as Obstruction.

**Comment by JeffWootton** [comment]
S-101PT13: No further action required. Close issue.
